CARD_STICKERS_CODES = {
    '2C' : 'CAACAgIAAxkBAAEOyCNoW8nC-wjUfX830svE3paEwQ_TwAAC_X0AAjTu2EpLrSkOG_kzhjYE',
    '2D' : 'CAACAgIAAxkBAAEOyCVoW8nNkZPRSfgJLuIkxyhcT5HlOQACT4AAAlfk2EpcDWWaYNNZWzYE',
    '2H' : 'CAACAgIAAxkBAAEOyCdoW8nU_nVh762gImRuytTCIlMLCgAC-H4AAtYV2EqNICLQYcV9cDYE',
    '2S' : 'CAACAgIAAxkBAAEOyCloW8ndvLjEc4CGnAYHv-iXcK9ZAwACW30AAjQ62EpxnWDKi_-AxzYE',

    '3C' : 'CAACAgIAAxkBAAEOyCtoW8wOogxsh4HreHEHapPd-gfNzQACRYMAArWB2EodF-bBNoKzbTYE',
    '3D' : 'CAACAgIAAxkBAAEOyDRoW85pYie0a_A7otTatvf_Qn6yOAACqmoAAop94EpccjnHnZgp2DYE',
    '3H' : 'CAACAgIAAxkBAAEOyDZoW85yPWKpoPXRKavUE9blygAB7XwAAnF2AAJPauBKmNF-_2VBepE2BA',
    '3S' : 'CAACAgIAAxkBAAEOyDhoW85362Lo1E6Pjkj5rC-p512PJwACvm0AAuv64EqyjQ9p1DaQNTYE',

    '4C' : 'CAACAgIAAxkBAAEOyDpoW86BzhGKAj1uQ6lI1WZwKexPHAAC2W0AAqwv4Ep-CfLifCUShjYE',
    '4D' : 'CAACAgIAAxkBAAEOyDxoW86NGd7EfdSOKuQRCwYqSX67rwACdGQAAsW84Eq4TG_cAVXYRjYE',
    '4H' : 'CAACAgIAAxkBAAEOyD5oW86Zaf-Z0RxbRVIV4Txqz7K5cQACKHQAAhOa4UoeBKv1SqYJzTYE',
    '4S' : 'CAACAgIAAxkBAAEOyEBoW86hYJFZrm94pA29XWMrZ2f-swACdXoAAstN2UqgOrZ_ja5lzTYE',

    '5C' : 'CAACAgIAAxkBAAEOyEJoW86yRBSLJFZZsaqgrViQ3jTX0AADbQACCxngSnI6Cl-cx8M6NgQ',
    '5D' : 'CAACAgIAAxkBAAEOyERoW868UOqSdb-gl65ONGtzb3FxGQACfXMAAnDV2ErPsizi7qIvfDYE',
    '5H' : 'CAACAgIAAxkBAAEOyEZoW87GuhWfCbFyXyAOeUkbLQYxFwAC5XsAAray2UomGICoriylHTYE',
    '5S' : 'CAACAgIAAxkBAAEOyEhoW87Sak5C5ol1d4pOQO4DTWYomwACUGsAAkiR4EoAARG_wQkkwvk2BA',

    '6C' : 'CAACAgIAAxkBAAEOyEpoW87aoMUaMpA2oNRTNVsFwqutMgACdnIAAiWB4UqDGjNmFCp_EDYE',
    '6D' : 'CAACAgIAAxkBAAEOyFFoW9BF0Bv5iHyINJWX4Jl8ZEAgWwACrXkAAvRa4EpV2SD4KAGVcDYE',
    '6H' : 'CAACAgIAAxkBAAEOyFNoW9BNBV44jB4kj1iNVj-1b2tQ0wACZmwAAvqw4UpZLD9ozjVk7jYE',
    '6S' : 'CAACAgIAAxkBAAEOyFVoW9BWJAWnv_sOx7Ql4XlOkpY02AACH34AAip_2UqKSoXdz0rbRDYE',

    '7C' : 'CAACAgIAAxkBAAEOyFdoW9DriJrX5Puq1KosF8JoUwPtPAAC_2oAAvtI4Eo8u2inDhADFTYE',
    '7D' : 'CAACAgIAAxkBAAEOyFloW9DuGRtTsq6sTW1FRUjUD42ZYgACMHsAAsKr2ErMRZfncjTRfTYE',
    '7H' : 'CAACAgIAAxkBAAEOyFtoW9DwePOeLLtRgfNLa4yPnueXvAACJW8AAtC64Er0ZexPCUEC-zYE',
    '7S' : 'CAACAgIAAxkBAAEOyF1oW9Dy2I3h1Oti_Yi_gF1mYJvddgACZnQAAs4O4Ep1cf8SkjggZDYE',

    '8C' : 'CAACAgIAAxkBAAEOyF9oW9D0w4SMye4VxFWEXRNM_pifRgACXHYAAjnA4UpuPCJXpWaL0DYE',
    '8D' : 'CAACAgIAAxkBAAEOyGFoW9D2wlGTNmTOncQtqaX9b4NkegADcwAChBHgSkUHxHqgB7ayNgQ',
    '8H' : 'CAACAgIAAxkBAAEOyGNoW9D4LKHz91_j1AvjQih0YKQlhQACcHQAAu0f4UobQD_f_dpzyzYE',
    '8S' : 'CAACAgIAAxkBAAEOyGVoW9D6MbWzdYcXqJNTNfM37Wg_4wACGngAAgK82Eoxzlos3kfMRzYE',

    '9C' : 'CAACAgIAAxkBAAEOyGdoW9D85VWMrT7h3V1ns__A0k8TcAACXncAAp8j2Eqr_lYiT8fb4TYE',
    '9D' : 'CAACAgIAAxkBAAEOyGloW9D9lWRJZnqNr1wh0pImxseEmQACrXoAAirV2EofT4bQ_X24rzYE',
    '9H' : 'CAACAgIAAxkBAAEOyGtoW9D_wMYIM9Qh2b3dvLlWR-PqHgAC4HsAAsFp2Uo23rNJLe8hrzYE',
    '9S' : 'CAACAgIAAxkBAAEOyG1oW9EBSEJd66MgR4g4sdfYhCyImAACWHMAAq4-4EpBHcug6_6m5TYE',

    '0C' : 'CAACAgIAAxkBAAEOyG9oW9EDcIKmSlP1sJZbMsAaQtZ-nAACVnYAAjKw2UpGQ7NxXVNzuzYE',
    '0D' : 'CAACAgIAAxkBAAEOyHFoW9EFdkWQptIchQWAJmvZKiBsugACi4AAAtxj2ErkXW3bDGR22zYE',
    '0H' : 'CAACAgIAAxkBAAEOyHNoW9EH_qCrxwdV0G7n6BZSFtITrQACgH0AAsvi2EpQWdnHLJURFzYE',
    '0S' : 'CAACAgIAAxkBAAEOyHVoW9EJHYu0TNHY6BZOXCj2IlNd5AAC43AAAtKa2UorkaQG9mmW3DYE',

    'JC' : 'CAACAgIAAxkBAAEOyHdoW9FkgLatbHIHioGDr0DrRvpWnQACvX0AAmHw2EpAvx2s03bg8TYE',
    'JD' : 'CAACAgIAAxkBAAEOyHloW9Fn8D0WOI_7WLHZoBgOL5m1aQACW3EAAiZZ4UrVe8gXQrnRlTYE',
    'JH' : 'CAACAgIAAxkBAAEOyHtoW9FoCH0yFJDFp1-OfFmts6VUsAACXG8AAqE-4UrPy7BnT_A9TDYE',
    'JS' : 'CAACAgIAAxkBAAEOyH1oW9FqV2zrvFwufswaBluTU6jeHgACT3oAAkpU2UqjspcvxHf3tzYE',

    'QC' : 'CAACAgIAAxkBAAEOyH9oW9FsvRMDETpWkn1NppPrwXfwlwACPnEAAiT24Uoc5RK78eGqeDYE',
    'QD' : 'CAACAgIAAxkBAAEOyIFoW9FucRmk56W8ksussNfFj3l9wQACb2gAAsQV4EplJm4mp4MrLTYE',
    'QH' : 'CAACAgIAAxkBAAEOyINoW9Fw6uqs2dvRqUAwYXmxpkYeegAChXgAAnAz2Urh7cd1izYP8zYE',
    'QS' : 'CAACAgIAAxkBAAEOyIVoW9FyWatQubUBk4RQ0uHPWvwiHQACrn0AAkW32EpXZc6qcaxbMDYE',

    'KC' : 'CAACAgIAAxkBAAEOyIdoW9F0TaLrolOOT04ZoiJjkIanjAACz3AAAk3N4Up6MMq7u1mOvzYE',
    'KD' : 'CAACAgIAAxkBAAEOyIloW9F3mYZDvTalSnwuDS3gGXzwZAAC7mcAAokB4UoFTXNoIGPQqjYE',
    'KH' : 'CAACAgIAAxkBAAEOyItoW9F5BkZCf3_xH_lhmxTxkYvH8AACPXgAAm8q2EpMVktqTqxlfTYE',
    'KS' : 'CAACAgIAAxkBAAEOyI1oW9GC-mPm-6e_pNjMDELA0vuiyAACb3YAAk-i2ErzJfIGXGgTuTYE',

    'AC' : 'CAACAgIAAxkBAAEOyI9oW9GE1KJ8lZiHbfU_CI0dQHe8hwACtHkAAmmi4EqxMwve9enHGTYE',
    'AD' : 'CAACAgIAAxkBAAEOyJFoW9GFauhC7POXT_ooipUvDJU2TQACjnMAAtw54UrsAYl7jvT7qDYE',
    'AH' : 'CAACAgIAAxkBAAEOyJNoW9GHPpfZ52cDMg0jxnzMw5jb1AACw2cAAkfY4UqrZFwjio4y3DYE',
    'AS' : 'CAACAgIAAxkBAAEOyJVoW9GJvtCLXUCgdI3xoQp--MjV0QACXngAAtq12Up5vm-WWHoQFDYE',

    'X1' : 'CAACAgIAAxkBAAEOyJdoW9GLMiW3BWIEKi7pnm_7hwHUDQACIH8AAj-N2EqonXR3A9QbRzYE',
    'X2' : 'CAACAgIAAxkBAAEOyJloW9GNT_6caxNLl75aPuifLdTRrAACwYkAAn8l2Eodq-EU44GjuDYE',

    'BACK' : 'CAACAgIAAxkBAAEOyJtoW9GPsLQaUJpxcTKiox7TKd_JEwACMmsAAkhk4ErZF26Hp2_xJDYE'
}

GAMES_CALLBACK_LINKS = {'pig' : 'https://en.wikipedia.org/wiki/Pig_(card_game)',}

CHANNELS_USERNAMES = {'@dasegos' : ('dasegos', 'https://t.me/dasegos'),}

GITHUB_SOURCE_CODE_LINK = 'https://github.com/dasegos/Pig-Card-Game-Bot'

DEVELOPER : str = 'flamme_ss'
INSTAGRAM_LINKS : list[str] = ['https://www.instagram.com/dasegos', ]
EMAIL_LINKS : list[str] = ['polina_semenova_pr.oj@mail.ru', 'dasego111@gmail.com']